### ISSUE TITLE
Durchschnitt Kcalverbrauch-Training

### ISSUE THREAD

**Issue by marcabg** [Vadime/FitnessApp#10]

**Comment by marcabg** [comment]
Training:
Leistungsumsatz: Frauen: 1 kcal x Körpergewicht (in KG) x (Stunden). 
Männer: 1,1 kcal x Körpergewicht (in KG) x 24

Für etwa 24-48 Stunden nach Deinem Krafttraining ist Dein Kalorienverbrauch durch den sogenannten Nachbrenneffekt deutlich erhöht. Diese Steigerung kommt hauptsächlich durch Regenerationsprozesse zustande, die Dein Körper nach dem Training durchführt.

oder Durchschnittlich:

folgenden Werte:
•	30 Min Krafttraining => ~ 180 kcal
•	45 Min Krafttraining => ~ 270 kcal
•	60 Min Krafttraining => ~ 360 kcal
•	90 Min Krafttraining => ~ 540 kcal
120 Min Krafttraining => ~ 720 kcal

**Comment by Vadime** [comment]
Das müssen wir in Verbindung mit #35 machen. Die Datenstruktur ist mir noch nicht klar... :(
