### ISSUE TITLE
Ist-Stand Dokumentieren (Video)

### ISSUE THREAD

**Issue by robert-hrmn** [Vadime/FitnessApp#20]
#14 

Video erreichbar unter:
https://youtu.be/4m1wT-0a2U0

**Comment by robert-hrmn** [comment]
Bitte einer Überprüfen

**Comment by Vadime** [comment]
Sieht super aus

**Comment by LennardSteinecke** [comment]
Sehr gutes Video. Top erklärt

**Comment by Felix9944** [comment]
gefällt mir, danke
