### ISSUE TITLE
Formel Kcalverbrauch (täglicher Bedarf)

### ISSUE THREAD

**Issue by marcabg** [Vadime/FitnessApp#9]

**Comment by marcabg** [comment]
**Grundumsatz Formeln**

Formel für den täglichen Verbrauch ohne äußerliche Einflüsse
Die sogenannte „Harris-Benedict-Formel“: 
655,1 + (9,6 x Körpergewicht in kg) + (1,8 x Körpergröße in cm) – (4,7 x Alter in Jahren)

Damit man das Abnehmen eine Person eine längere Zeit auch durchhalten kann, empfiehlt sich ein Kaloriendefizit von etwa 300-500 kcal

Unter 1400 bis 1700 kcal sollte die Energiezufuhr allerdings niemals liegen.

**Comment by Vadime** [comment]
Habe jetzt den Leistungsumsatz hinzugefügt.
Das müssen wir uns nochmal angucken mit @marcabg .
#acfe0d0dff38130152c1e32d9feb807a0c88e77
